version: '3.4'
# author: RÃ©mi Venant, <remi.venant@univ-lemans.fr>

services:
  mysqldb:
    image: mariadb:10.4
    env_file:
      - environment/dev/mysql.env
    environment:
      - MYSQL_ROOT_PASSWORD=lSj58osiU12kjdj43shaSDDz
    volumes:
      - mysql-data:/var/lib/mysql
      - ../databasesInit/mysql/dev:/docker-entrypoint-initdb.d:ro
    networks:
      lpdiwa-net:
        aliases:
          - mysqldb
    restart: always

  mongodb:
    image: mongo:4.2
    env_file:
      - environment/dev/mongo.env
    volumes:
      - mongo-data:/data/db
      - ../databasesInit/mongo/dev:/docker-entrypoint-initdb.d:ro
    networks:
      lpdiwa-net:
        aliases:
          - mongodb
    restart: always

  symfony:
    build:
      context: ./symfony
      args:
        - http_proxy=http://vproxy.univ-lemans.fr:3128
        - https_proxy=http://vproxy.univ-lemans.fr:3128
        - no_proxy=127.0.0.1,localhost
    env_file:
      - environment/lemans-proxy.env
      - environment/dev/symfony.env
    volumes:
      - ./symfony/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./symfony/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ../site:/var/www/site
      - site-vendor:/var/www/site/vendor
    working_dir: /var/www/site
    networks:
      lpdiwa-net:
        aliases:
          - symfony
    restart: always
    command: bash -c "composer install && php-fpm"

  http:
    image: nginx:1.19-alpine
    depends_on:
      - symfony
    volumes:
      - ../site:/var/www/site:ro
      - ./http/server-dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      lpdiwa-net:
        aliases:
          - httpsrv
    ports:
      - 127.0.0.1:8080:80
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    env_file:
      - environment/lemans-proxy.env
      - environment/dev/phpmyadmin.env
    volumes:
      - /sessions
    networks:
      lpdiwa-net:
        aliases:
          - phpmyadmin
    ports:
      - 127.0.0.1:8888:80
    restart: always

volumes:
  site-vendor:
  mysql-data:
  mongo-data:

networks:
  lpdiwa-net:
